version: "3"
services: 
  registry:
    image: registry:2
    ports:
    - 127.0.0.1:5000:5000
    volumes:
    - /var/lib/registry:/var/lib/registry
    #- ../Nginx/certs:/certs
    - ./auth:/auth
    container_name: registry
    restart: always
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_VALIDATION_DISABLED=true
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      #- REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.otokaze.cn.pem
      #- REGISTRY_HTTP_TLS_KEY=/certs/registry.otokaze.cn.key
