version: '3'
services:
  gittea:
    image: gitea/gitea:latest
    volumes:
      - /opt/gitea:/data
    ports:
      - "3000:3000"
      - "3022:22"
    container_name: qa-gitea
    restart: always
    environment: 
      - TZ=Asia/Shanghai

